config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tags#_landing'
  resources :tags do
    collection do
      get 'search'
    end
  end
  resources :users, only: :show
  resources :projects do
    resources :comments, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :text_comment, presence: true

  belongs_to :project
  belongs_to :user
end

app/models/project.rb
class Project < ApplicationRecord
  validates :main_title,      presence: true
  validates :start_date,      presence: true
  validates :finish_date,     presence: true
  validates :department,      presence: true
  validates :category,        presence: true
  validates :project_memo,    presence: true
  validates :image,           presence: :true
  
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_one_attached :image
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :text_tag, :text_memo, :color, presence: true
  belongs_to :user

  def self.search(search)
    if search != ""
      Tag.where('text_tag LIKE(?)', "%#{search}%")
    else
      Tag.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tags

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    tags_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :name_kana, :nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to project_path(@comment.project)
    else
      @project = @comment.project
      @comment = @project.comments.includes(:user)
      render "projects/show"
    end
  end


  private
  def comment_params
    params.require(:comment).permit(:text_comment).merge(user_id: current_user.id, project_id: params[:project_id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.includes(:user).order("created_at DESC")
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to root_path
    else
      render :new
    end
  end

  
  def show
    @project = Project.find(params[:id])
    @comment = Comment.new
    @comments = @project.comments.includes(:user)
  end

  def edit
    @project = Project.find(params[:id])
    unless current_user = @project.user
      redirect_to root_path
    end
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      redirect_to project_path(@project)
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to root_path
  end

  private
  def project_params
    params.require(:project).permit(:main_title, :start_date, :finish_date, :department, :category, :project_memo, :image).merge(user_id: current_user.id)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_params, only: [:edit, :show]

  def index
    @tags = Tag.includes(:user).order("created_at DESC").limit(5)
    @projects = Project.includes(:user).order("created_at DESC")
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.create(tag_params)
  end

  def destroy
    tag = Tag.find(params[:id])
    tag.destroy
  end

  def edit
  end

  def update
    tag = Tag.find(params[:id])
    tag.update(tag_params)
  end

  def show
    @tag = Tag.find(params[:id])
  end

  def search
    @tags = Tag.search(params[:keyword])
  end

  private
  def tag_params
    params.require(:tag).permit(:text_tag, :text_memo, :color).merge(user_id: current_user.id)
  end

  def find_params
    @tag = Tag.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    if user_signed_in? && current_user.id 
      @nickname = current_user.nickname
      @tags = current_user.tags
    else
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> Borderless</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="title">
      　<img id="borderless" src="/assets/Borderless.jpg" alt="">
        <%= link_to ' Borderless', tags_path %>
        <p class="sub">自分の好きなこと、経験が誰かのためになる</p>
        <div class="login">
          <div class="login_font">
            <!-- ログイン有無の条件分岐 -->
            <% if user_signed_in? %>
              <%= link_to current_user.nickname, user_path(current_user.id), method: :get %>
              <%= link_to '【ログアウト】', destroy_user_session_path, method: :delete %>
            <% else %>
              <%= link_to '【ログイン】', new_user_session_path %>
              <%= link_to '【新規登録】', new_user_registration_path %>
            <% end %>
          </div>
        </div>
      </div>
    </header>
    <main>
      <%= yield %>
    </main>
    <footer>
      <%= link_to '【back】', :back %>
      <div class="footer2">
        Copyright Borderless 2021.
      </div>
    </footer>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with model: @project, local: true do |f| %>
  <div class="">
    <%= f.label :main_title, "【プロジェクト名】" %><br />
    <%= f.text_field :main_title %>
  </div>

  <div class="">
    <%= f.label :start_date, "【開始日】" %><br />
    <%= f.text_area :start_date %>
  </div>

  <div class="">
    <%= f.label :finish_date, "【終了日】" %><br />
    <%= f.text_area :finish_date %>
  </div>

    <div class="">
    <%= f.label :department, "【所属/部署】" %><br />
    <%= f.text_area :department %>
  </div>

  <div class="">
    <%= f.label :category, "【投稿カテゴリー】" %><br />
    <%= f.text_area :category %>
  </div>

  <div class="">
    <%= f.label :project_memo, "【内容】" %><br />
    <%= f.text_area :project_memo %>
  </div>

  <div class="">
    <%= f.label :image, "【プロジェクト関連の画像】" %><br />
    <%= f.file_field :image %>
  </div>

  <div class="">
    <%= f.submit "作成する", class: :form__btn %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="">【プロジェクト編集】</h2>
<%= render partial: "form", locals: { project: @project } %>

app/views/projects/new.html.erb
<div class="">新規プロジェクト投稿</h2>
<%= render partial: "form", locals: { project: @project } %>

app/views/projects/show.html.erb
<!-- プロジェクト詳細 -->
<div class="card_wrapper">
  <p>【プロジェクト名】: <%= link_to "#{@project.main_title}", projects_path(@project.id) %></p>
  <div class="card">
    <%= link_to image_tag(@project.image), class: :img %>
    <div>
      <p>【開始日】: <%= link_to "#{@project.start_date}", projects_path(@project.id) %></p>
      <p>【終了日】: <%= link_to "#{@project.finish_date}",projects_path(@project.id) %></p>
      <ul>
        <li>
          <p>【担当部署】: <%= link_to "#{@project.department}", projects_path(@project.id) %></p>
        </li>
        <li>
          <p>【カテゴリー】: <%= link_to "#{@project.category}", projects_path(@project.id) %></p>
        </li>
        <li>
          <p>【内容】: <%= link_to "#{@project.project_memo}", projects_path(@project.id) %></p>
        </li>
        <li>
          <%= link_to "by.#{@project.user.nickname}", user_path(@project.user) %>
          <% if user_signed_in? && current_user.id == @project.user_id%>
            <li>
              <%= link_to '【編集】', edit_project_path(@project.id), method: :get %>
            </li>
            <li>
              <%= link_to '【削除】', project_path(@project.id), method: :delete %>
            </li>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
  <!-- コメント投稿欄 -->
  <div class="prototype__comments">
    <% if current_user %>
      <%= form_with(model: [@project,@comment],local: true) do |f| %>
        <div class="field">
          <%= f.label :text_comment, "<コメント欄>" %><br />
          <%= f.text_field :text_comment %>
        </div>
        <div class="actions">
          <%= f.submit "送信する", class: :form__btn  %>
        </div>
      <% end %> 
    <% end %>
    <% if @comments%>
      <ul class="comments_lists">
        <% @comments.each do |comment| %>
        <li class="comments_list">
          <%= comment.text_comment %>
          <p>by.<%= link_to comment.user.nickname, user_path(comment.user) %>
        </li>
        <% end %>
      </ul>
    <% end %>
  </div>
</div>

app/views/tags/_landing.html.erb
<p class="sub">自分の好きなこと、経験が誰かのためになる</p>
<div id="landing">
  <ul>
    <li>履歴書などでは表現仕切れない魅力の</li>
    <li>コミュニティ内での横断した情報共有や人材発見</li>
    <li>新規事業やアイデアのブラッシュアップ</li>
  </ul>

</div>
<%= link_to '一覧ページへ', tags_path %>

app/views/tags/_tag.html.erb
<!-- 投稿タグ一覧 -->
<div class="tag_wrapper">
  <p class="tag_name" ><タグ一覧></p>
  <div class="tag">
  <% @tags.each do |tag| %>
    <div style="background-color:<%= tag.color %>">
      <p class="tag1">  ＃<%= link_to tag.text_tag, tag_path(tag.id) %></p>
      <p class="tag1">【Memo】<%= link_to tag.text_memo, tag_path(tag.id) %></p>
      <p class="tag1">by.<%= link_to tag.user.nickname, user_path(tag.user.id), method: :get %></p>
    </div>
  <% end %>
</div>

app/views/tags/create.html.erb
<div class="">
  <div class="">
    <h3>作成が完了しました</h3>
    <%= link_to 'ユーザページへ戻る', tags_path %>

app/views/tags/destroy.html.erb
<div class="">
  <div class="">
    <h3>削除が完了しました</h3>

app/views/tags/edit.html.erb
<div class="">
  <div class="">
    <h3>タグを編集する</h3>
    <%= form_with(model: @tag, local: true) do |form| %>
      <%= form.text_field :text_tag, placeholder: "tag" %>
      <%= form.text_field :text_memo, placeholder: "memo" %>
      <%= form.submit "MAKE" %>
    <% end %>
  </div>
</div>

app/views/tags/index.html.erb
<div class="main">
  <!--検索欄 -->
  <div class="search">
    <%= form_with(url: search_tags_path, local: true, method: :get, class: "") do |form| %>
      <%= form.text_field :keyword, placeholder: "タグを検索する", class: "" %>
      <%= form.submit "検索" %>
    <% end %>
  </div>
  
  <!-- 投稿タグ一覧 -->
  <div class="tag_wrapper">
    <p class="tag_name" ><新着タグ一覧></p>
    <div class="tag">
      <% @tags.each do |tag| %>
        <div class="tag-card" style="background-color:<%= tag.color %>">
          <p class="tag1-font">  ＃<%= link_to tag.text_tag, tag_path(tag.id) %></p>
          <p class="tag1"><%= tag.text_memo %></p>
          <p class="tag1">by.<%= link_to tag.user.nickname, user_path(tag.user.id), method: :get %></p>
        </div>
      <% end %>
    </div>
  </div>
  
  <!-- プロジェクト一覧 -->
  <div class="project">
    <p class="project_name"><新着プロジェクト一覧></p>
    <div class="card">
      <% @projects.each do |project| %>
        <div class="card_body">
          <p>【プロジェクト名】: <%= link_to project.main_title, project_path(project.id) %></p>
          <p>【カテゴリー】: <%= link_to project.category, project_path(project.id) %></p>
          <%= link_to image_tag(project.image), class: :img %>
          <p>【開始日】：<%= project.start_date %></p>
          <p>【終了日】：<%= project.finish_date %></p>
          <p>by.<%= link_to project.user.nickname, user_path(project.user.id) %></p>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tags/new.html.erb
<div class="cp_iptxt">
  <h3>タグを作成する</h3>
  <%= form_with(model: @tag, local: true) do |form| %>
    <%= form.text_field :text_tag, placeholder: "tag" %>
    <%= form.text_field :text_memo, placeholder: "memo" %>
    <p>【Color】<%= form.color_field :color %></p>
    <%= form.submit "作成する" %>
  <% end %>
</div>

app/views/tags/search.html.erb
<%= form_with(url: search_tags_path, local: true, method: :get, class: "") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "" %>
  <%= form.submit "検索", class: "" %>
<% end %>
<div class="">
  <% @tags.each do |tag| %>
    <div class="" style="">
      <p><%= tag.text_tag %></p>
      <span class="">
      </span>
    </div>
    <a href="/users/<%= tag.user.id %>">
      <span>投稿者 </span><%= tag.user.nickname %>
    </a>
    <li>
      <%= link_to '詳細', tag_path(tag.id), method: :get %>
    </li>
    <% if user_signed_in? && current_user.id == tag.user_id%>
      <li>
        <%= link_to '編集', edit_tag_path(tag.id), method: :get %>
      </li>
      <li>
        <%= link_to '削除', tag_path(tag.id), method: :delete %>
      </li>
    <% end %>
  <% end %>
</div>

app/views/tags/show.html.erb
<div class="tag_wrapper">
  <p class="tag_name" ><タグ一覧></p>
  <div class="tag">
    <div style="background-color:<%= @tag.color %>">
      <p class="tag1">＃<%= @tag.text_tag %></p>
      <p class="tag1">【Memo】<%= @tag.text_memo %></p>
      <p><%= @tag.updated_at %></p>
      <p class="tag1">by.<%= @tag.user.nickname %></p>
    </div>
  </div>
</div>

app/views/tags/update.html.erb
<div class="">
  <div class="">
    <h3>編集が完了しました</h3>
    <%= link_to 'ユーザページへ戻る', tags_path %>

app/views/users/show.html.erb
<!-- current_userページ -->
<div class="header2">
  <%= link_to "【New Tag】", new_tag_path %>
  <%= link_to "【New project】", new_project_path %>
</div>

<div class="tag-main">
  <p><%= @nickname %>さんのTag一覧</p>
  <% @tags.each do |tag| %>
    <div style="background-color:<%= tag.color %>">
      <p>＃<%= tag.text_tag %></p>
      <p>【Memo】<%= tag.text_memo %></p>
      <% if user_signed_in? && current_user.id == tag.user_id %>
        <%= link_to '編集', edit_tag_path(tag.id), method: :get %>
        <%= link_to '削除', tag_path(tag.id), method: :delete %>
      <% end %>
    </div>
  <% end %>
</div>